server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
#    primary:
      # mysqlXADataSource 需要url 而不是jdbc-url
    url: jdbc:mysql:///demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:generator:/*.xml
logging:
  level:
    com.aricsun.boot.launch: debug
#    secondary:
#      url: jdbc:mysql:///demo2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver

# 由于使用Mybatis，以下配置停用
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: validate
#    database: mysql
#    show-sql: true
#  jta:
#    atomikos:
#      datasource:
#        max-pool-size: 20
#        borrow-connection-timeout: 60
#      connectionfactory:
#        max-pool-size: 20
#        borrow-connection-timeout: 60


# 设置盐值（加密解密密钥），我们配置在这星只是为了测试方便
# 生产坏境中，切记不要这样直接进行设置，可通过环境变量、命令行等形式进行设置。
# java -jar boot-launch-1.0.jar --jasypt.encryptor.password=123456
jasypt:
  encryptor:
    password: 123456

# 由于使用SpringDataJPA，此部分停用
#primarydb:
#  uniqueResourceName: primary
#  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
#  xaProperties:
#    url: jdbc:mysql:///demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#    user: root
#    password: root
#  exclusiveConnectionMode: true
#  minPoolSize: 3
#  maxPoolSize: 10
#  testQuery: select 1 from dual  # 由于采用HikiriCP，用于检测数据库连接是否存活
#
#secondarydb:
#  uniqueResourceName: secondary
#  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
#  xaProperties:
#    url: jdbc:mysql:///demo2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#    user: root
#    password: root
#  exclusiveConnectionMode: true
#  minPoolSize: 3
#  maxPoolSize: 10
#  testQuery: select 1 from dual