# 外部tomcat是不会对下面端口生效的，还是得看tomcat/conf/server.xml
#server:
#  port: 8888
  # 以下代码配置http端口，使其能够跳转到https的8888端口上
#  httpPort: 80
  # 调整嵌入式容器（Tomcat等）的运行参数，第一种方法，修改配置文件，如下
#  tomcat:
#    max-connections: 8192
#  ssl:
#    key-store: classpath:otherconfig/aricsun-ssL-key.p12
#    key-store-password: 123456
#    key-store-type: PKCS12

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
#    primary:
      # mysqlXADataSource 需要url 而不是jdbc-url
    url: jdbc:mysql:///demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    cache: false  # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/

# 第三种注册自定义事件监听器的方法
context:
  listener:
    classes: com.aricsun.boot.launch.config.event.MyListener3

mybatis:
  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.aricsun.boot.launch: debug
#    secondary:
#      url: jdbc:mysql:///demo2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver

# 由于使用Mybatis，以下配置停用
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: validate
#    database: mysql
#    show-sql: true
#  jta:
#    atomikos:
#      datasource:
#        max-pool-size: 20
#        borrow-connection-timeout: 60
#      connectionfactory:
#        max-pool-size: 20
#        borrow-connection-timeout: 60


# 设置盐值（加密解密密钥），我们配置在这星只是为了测试方便
# 生产坏境中，切记不要这样直接进行设置，可通过环境变量、命令行等形式进行设置。
# java -jar boot-launch-1.0.jar --jasypt.encryptor.password=123456
jasypt:
  encryptor:
    password: 123456

# 由于使用SpringDataJPA，此部分停用
#primarydb:
#  uniqueResourceName: primary
#  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
#  xaProperties:
#    url: jdbc:mysql:///demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#    user: root
#    password: root
#  exclusiveConnectionMode: true
#  minPoolSize: 3
#  maxPoolSize: 10
#  testQuery: select 1 from dual  # 由于采用HikiriCP，用于检测数据库连接是否存活
#
#secondarydb:
#  uniqueResourceName: secondary
#  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
#  xaProperties:
#    url: jdbc:mysql:///demo2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
#    user: root
#    password: root
#  exclusiveConnectionMode: true
#  minPoolSize: 3
#  maxPoolSize: 10
#  testQuery: select 1 from dual