server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  # 1.一个家庭月爸爸、妈妈、孩子。
  # 2.这个家庭有一个名字（family-name）叫做“happy family"
  # 3.爸爸有名字（name）和年龄（age）两个属性
  # 4.妈妈有两个别名
  # 5.孩子除了名字（name）和年龄（age）两个属性，还有一个friends的集合
  # 6.每个friend有两个属性：hobby（爱好）和性别（sex）

family:
  family-name: "happy family"
  father:
    name: zimug
    age: ${random.int(0,100)}
  mother:
    alias:
      - lovely
      - ailice
  child:
    name: ${family.father.name:zimug2}
    age: 5
    friends:
      - hobby: fottball
        sex: male
      - hobby: basketball
        sex: female